# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 04:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_scrum_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationkey',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 4, 38, 57, 403810, tzinfo=utc)),
        ),
    ]
