# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_scrum_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumscrumuser',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
