# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 09:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_scrum_api', '0002_auto_20171221_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumscrumusertoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
