# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum_scrum_api', '0004_auto_20171220_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumscrumuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
